### PR TITLE
fix keyword argument usage for ruby 3

### PR DESCRIPTION
**Pull request by fnordfish**

### CODE REVIEW

**Comment by paul-at** [comment]
Thank you for you PR @fnordfish !

A few Qs before it can be merged:

- What's a 'service overwrite'? Any comments of what this change does?
- Couldn't quickly find any documentation for ActiveStorage::Blob.services - could you point me to the right place to look?
- Does adding service name changes anything about how this gem should be configured?
- Do changes require a specific minimum Rails version?

**Comment by fnordfish** [comment]
Hi. Sorry for the late replay.

Indeed, this is a fix for newer Rails versions in which you can configure multiple services (in `config/storage.yml` / `config/storage/#{Rails.env}.yml`) and use them independently.

`ActiveStorage::Blob.services` is a `ActiveStorage::Service::Registry` with all your `config/storage` configured `ActiveStorage::Service` instances.

By "service overwrite" I meant that you are now able to set a specific service for an attachment like this:

```ruby
# the default setting in your app config
config.active_storage.service = :local

# ... can be overwritten on an attachment like this
class User < ApplicationRecord
  has_one_attached :avatar, service: :s3
end
```

`ActiveStorage::Blob.services` appeared in Rails 6.1.0

**Comment by paul-at** [comment]
Thank you so much for the detailed explanation @fnordfish 

May I ask you to bump the Rails version in the .gemspec before I merge the PR? I understand the usage of the gem is unchanged, but if there's anything you feel is needed to be added to the readme, please do it as well.

**Comment by fnordfish** [comment]
@paul-at Done.

**Pull request merged**
