### PR TITLE
Updated to work with Rails 5.2.3

### PR DESCRIPTION
**Pull request by markaschneider**

### CODE REVIEW

**Comment by markaschneider** [comment]
Hi, any update on when you'll have a chance to review and merge this?

**Comment by bjgaynor** [comment]
Merge this please!

**Comment by gr8bit** [comment]
Great PR!
@paul-at would you please review/merge this?

**Comment by paul-at** [comment]
Merged, thank you @markaschneider @bjgaynor @gr8bit !

**Pull request merged**
